"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

function parseLine(line: string) { const cells: string[] = []; let value = ""; let quoted = false; for (let i = 0; i < line.length; i++) { const char = line[i]; if (char === '"' && line[i + 1] === '"') { value += '"'; i++; } else if (char === '"') quoted = !quoted; else if (char === ',' && !quoted) { cells.push(value.trim()); value = ""; } else value += char; } cells.push(value.trim()); return cells; }
export default function BulkUpload({ userId, sellerName }: { userId: string; sellerName: string }) {
  const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function upload(file: File) { setLoading(true); setMessage(""); const lines = (await file.text()).split(/\r?\n/).filter(Boolean); const headers = parseLine(lines.shift() || "").map((h) => h.toLowerCase()); const required = ["title","description","price","condition","category","location","image_url"]; if (!required.every((h) => headers.includes(h))) { setMessage(`Missing required columns: ${required.filter((h) => !headers.includes(h)).join(", ")}`); setLoading(false); return; } const rows = lines.slice(0, 500).map((line) => { const values = parseLine(line); const row = Object.fromEntries(headers.map((header, index) => [header, values[index] || ""])); return { user_id: userId, seller_name: sellerName, title: row.title, description: row.description, price: Number(row.price), condition: row.condition, category: row.category, location: row.location, image_url: row.image_url, image_urls: [row.image_url], trade: ["true","yes","1"].includes(row.trade.toLowerCase()), status: "active" }; }); const supabase = createClient(); const { error } = await supabase.from("listings").insert(rows); if (error) setMessage(error.message); else setMessage(`${rows.length} listings uploaded successfully.`); setLoading(false); }
  return <div className="bulk-upload"><label className="upload-zone"><strong>{loading ? "Uploading inventory..." : "Choose a CSV file"}</strong><span>Maximum 500 rows</span><input type="file" accept=".csv,text/csv" disabled={loading} onChange={(e) => { const file = e.target.files?.[0]; if (file) upload(file); }} /></label>{message && <p className={message.includes("successfully") ? "form-message success" : "form-message error"}>{message}</p>}<a className="inline-link" download="anypart-gear-template.csv" href="data:text/csv;charset=utf-8,title%2Cdescription%2Cprice%2Ccondition%2Ccategory%2Clocation%2Cimage_url%2Ctrade%0AExample%20part%2CAdd%20at%20least%2010%20characters%2C100%2CGood%2CCar%20Parts%2CBay%20Shore%2Chttps%3A%2F%2Fexample.com%2Fphoto.jpg%2Cfalse">Download CSV template</a></div>;
}

