import Link from "next/link";
import { redirect } from "next/navigation";
import { getUser } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { ReportAction, VerifyShop } from "./moderation-actions";

type Report={id:string;reason:string;details:string|null;status:string;created_at:string;listings:{title:string}|null};
type Shop={id:string;name:string;specialty:string;location:string;is_verified:boolean;is_active:boolean};
export const dynamic="force-dynamic";
export default async function AdminPage(){const user=await getUser();if(!user)redirect("/login?next=/admin");if(user.app_metadata?.role!=="admin")redirect("/account");const supabase=await createClient();const [{data:reports},{data:shops}]=await Promise.all([supabase.from("reports").select("id,reason,details,status,created_at,listings(title)").order("created_at",{ascending:false}).limit(100),supabase.from("shops").select("id,name,specialty,location,is_verified,is_active").order("created_at",{ascending:false}).limit(100)]);return <main><header className="simple-header"><div className="shell nav-wrap"><Link href="/" className="brand"><span className="brand-mark">APG</span><span className="brand-copy"><strong>Anypart</strong><small>&amp; Gear</small></span></Link><Link href="/account">My account</Link></div></header><div className="shell page-shell"><div className="page-intro"><span className="kicker">Owner controls</span><h1 className="page-title">Trust &amp; Safety</h1><p>Review member reports and approve verified businesses.</p></div><h2>Listing reports</h2><div className="admin-list">{(reports as unknown as Report[]||[]).map(r=><article className="admin-row" key={r.id}><div><strong>{r.reason}</strong><p>{r.listings?.title||"Removed listing"}</p>{r.details&&<small>{r.details}</small>}</div><ReportAction id={r.id} status={r.status}/></article>)}{!reports?.length&&<p>No reports waiting.</p>}</div><h2 className="admin-section">Business verification</h2><div className="admin-list">{(shops as Shop[]||[]).map(s=><article className="admin-row" key={s.id}><div><strong>{s.name}</strong><p>{s.specialty} · {s.location}</p><small>{s.is_verified?"Verified":"Not verified"}</small></div><VerifyShop id={s.id} verified={s.is_verified}/></article>)}{!shops?.length&&<p>No shops registered yet.</p>}</div></div></main>}
